apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongoapp
  template:
    metadata:
      labels:
        app: mongoapp
    spec:
      containers:
      - name: mongo-server
        image: mongo
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongoapp
#service  needs to forward a request it gets to the endpoints pods
#it can check which pod belong to it using slector in deployment and which one it should forward the request to using the selector in service.
  ports:
    - protocol: TCP
      port: 27017 #service is accessible within the cluster using its own ip port
      targetPort: 27017  #container port of the deployment
#which port it should forward the request to the pods

